version: 2
root-markers:
  - .git/
log-file: /Users/justinpxrk/.local/state/efm-langserver/log
log-level: 1
format-debounce: 0.5s
lint-debounce: 0.5s
provide-definition: false
triggers-chars: []
commands: []
tools: {}
languages: {}
