version: 2
root-markers:
  - .git/
log-file: $XDG_STATE_HOME/efm-langserver/log
log-level: 1
format-debounce: 1s
lint-debounce: 1s
provide-definition: false
triggers-chars: []
commands: []
languages: {}
tools: []
